#!/usr/bin/env python3
"""Unit tests to verify exceptions.
"""

#end_pymotw_header
import unittest


def raises_error(*args, **kwds):
    raise ValueError('Invalid value: ' + str(args) + str(kwds))


class ExceptionTest(unittest.TestCase):

    def testTrapLocally(self):
        try:
            raises_error('a', b='c')
        except ValueError:
            pass
        else:
            self.fail('Did not see ValueError')

    def testAssertRaises(self):
        self.assertRaises(
            ValueError,
            raises_error,
            'a',
            b='c',
        )

    def testAssertRaisesContext(self):
        with self.assertRaises(ValueError):
            raises_error('a', b='c')
